#pragma config(Sensor, S1,     line_follower_left, sensorEV3_Color)
#pragma config(Sensor, S2,     line_follower_right, sensorEV3_Color)
#pragma config(Sensor, S3,     HT_color_l,               sensorI2CCustom)
#pragma config(Sensor, S4,     HT_color_r,               sensorI2CCustom)
#pragma config(Motor,  motorA,          motor_grab,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          motor_drive_left, tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          motor_drive_right, tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          motor_dropper, tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lib/minmaxclip.h"
#include "lib/colorV2jester.h"
#include "lib/driveModule.h"

#pragma debuggerWindows("debugStream");

#define color_left S3
#define color_right S4

#define borderW 90

// FLAGS for ITC
bool dropped = false;
bool reset = false;



//_dropDrink()
task dropDrink() {
	dropped = false;
	setMotorTarget(motor_dropper, -200, 20);
	waitUntilMotorStop(motor_dropper);
	delay(500);
	setMotorTarget(motor_dropper, -5, 40);
	waitUntilMotorStop(motor_dropper);
	dropped = true;
}

// _resetStart
task resetStart()
{
	setMotorSpeed(motor_dropper, 10);
	setMotorSpeed(motor_grab, -25);
	wait1Msec(2000);
	setMotorSpeed(motor_dropper, 0);
	setMotorSpeed(motor_grab, 0);
	resetMotorEncoder(motor_dropper);
	wait1Msec(200);
	setMotorTarget(motor_dropper, -10, 10);
	waitUntilMotorStop(motor_dropper);
	resetMotorEncoder(motor_grab);
	resetMotorEncoder(motor_dropper);
	playTone(440, 10);
	reset = true;
}

//_pickupSingleBottle
void pickupSingleBottle() {
	setMotorTarget(motor_grab, 300, 30);
	waitUntilMotorStop(motor_grab);
	setMotorTarget(motor_grab, 70, 15);
	waitUntilMotorStop(motor_grab);
	setMotorTarget(motor_grab, 65, 15);
	delay(20);
	setMotorTarget(motor_grab, 120, 15);
	waitUntilMotorStop(motor_grab);
}




//_dropLB
void dropLB() {
	setMotorTarget(motor_dropper, -100, 30);
	waitUntilMotorStop(motor_dropper);
	setMotorTarget(motor_dropper, -200, 65);
	waitUntilMotorStop(motor_dropper);
	delay(500);
	setMotorTarget(motor_dropper, -10, 60);
	delay(500);
}

//_end
void end() {
	brake(0, 0);
	resetMotorEncoder(motor_drive_right);
	lfPDcm(15, 8);
	lfPDend(15);
	resetMotorEncoder(motor_drive_right);
	speedChange(15, 40);
	driveCm(40, 40, 18.0);
	brake(40, 23.0);
	turn(0, 40, 0, 0, 44);
	setMotorTarget(motor_grab, 5, 30);
}

// _main
task main()
{
	clearDebugStream();
	setMotorBrakeMode(motorA, motorBrake);
	setMotorBrakeMode(motorB, motorBrake);
	setMotorBrakeMode(motorC, motorBrake);
	setMotorBrakeMode(motorD, motorBrake);
	if (!verifySetupHTCOL(S3) || !verifySetupHTCOL(S4)) {
		writeDebugStreamLine("[INIT] SENSOR ERROR, check ht colors");
	}
	startTask(resetStart);
	eraseDisplay();
	waitUntil(reset);
	setLEDColor(ledGreen);
	waitForButtonPress();
	eraseDisplay();
	setLEDColor(ledOff);
	delay(150);
	clearTimer(T4);


	turn(0, -40, 0, 0, 44.0);
	driveCm(40, 40, 11.0);
	resetMotorEncoder(motor_drive_right);
	setMotorTarget(motor_grab, 520, 30);
	lfPDline(40, true, true);

	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 10.0);
	lfPDline(40, true, true);
	resetMotorEncoder(motor_drive_right);
	brake(40, 8.5);
	delay(250);

	// pickup drink 1 at green area
	turn(0, -40, 0, tireDistance/2, 27.5);
	turn(0, -40, 0, -tireDistance/2, 27.5);

	brake(0,0);
	pickupSingleBottle();


	turn(0, -40, 0, -tireDistance/2, 27.5);
	turn(0, -40, 0, tireDistance/2, 27.5);

	turn(0, 40, 0, 0, 178);
	lfPDline(15, true, true);

	// transfer to second side goto

	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 18.0);
	driveCm(40, 40, 63.0);
	setMotorTarget(motor_grab, 520, 30);
	lfPDline(15, true, true);

	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 10.0);
	lfPDline(40, true, true);
	resetMotorEncoder(motor_drive_right);
	brake(40, 8.5);
	delay(250);

	// pickup drink 2 at yellow area
	turn(0, -40, 0, tireDistance/2, 27.5);
	turn(0, -40, 0, -tireDistance/2, 27.5);

	brake(0,0);
	pickupSingleBottle();


	turn(0, -40, 0, -tireDistance/2, 27.5);
	turn(0, -40, 0, tireDistance/2, 27.5);

	lfPDline(40, true, true);
	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 10.0);
	brake(40, 15.0);
	setMotorTarget(motor_grab, 520, 30);
	turn(0, 40, 0, 0, 180);

	lfPDline(40, true, true);
	resetMotorEncoder(motor_drive_right);
	brake(40, 8.5);
	delay(250);

	// pickup 1 green block at blue
	turn(0, -40, 0, tireDistance/2, 27.5);
	turn(0, -40, 0, -tireDistance/2, 27.5);

	brake(0,0);
	pickupSingleBottle();

	delay(250);
	setMotorTarget(motor_grab, 320, 30);
	turn(0, -40, 0, -tireDistance/2, 27.5);
	turn(0, -40, 0, tireDistance/2, 27.5);



	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 25.0);
	lfPDline(40, true, true);
	resetMotorEncoder(motor_drive_right);
	brake(40, 7.0);

	// turn to the tables

	turn(0, -40, 0, 0, 90);

	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 15.0);
	turn(0, 40, 0, 19.5, 88.0);
	resetMotorEncoder(motor_drive_right);
	lfPDline(15, true, true);

	brake(0,0);
	delay(250);
	resetMotorEncoder(motor_drive_right);
	driveCm(-40, -40, 32.0);
	brake(0,0);

	dropped = false;
	startTask(dropDrink);
	waitUntil(dropped);

	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 65);
	brake(40, 70);

	dropped = false;
	startTask(dropDrink);
	waitUntil(dropped);

	resetMotorEncoder(motor_drive_right);
	driveCm(-40, -40, 11.0);
	turn(0, 40, 0, 19.5, 88.0);

	lfPDline(15, true, true);
	resetMotorEncoder(motor_drive_right);
	lfPDcm(15, 7.0);

	turn(0, -40, 0, 0, 89.0);

	lfPDline(40, true, true);

	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 10.0);
	brake(40, 15.0);
	setMotorTarget(motor_grab, 520, 30);
	turn(0, 40, 0, 0, 180);

	lfPDline(40, true, true);
	resetMotorEncoder(motor_drive_right);
	brake(40, 8.5);
	delay(250);

	// pickup 1 green block at blue
	turn(0, -40, 0, tireDistance/2, 27.5);
	turn(0, -40, 0, -tireDistance/2, 27.5);

	brake(0,0);
	pickupSingleBottle();
	delay(250);
	setMotorTarget(motor_grab, 320, 30);
	turn(0, -40, 0, -tireDistance/2, 27.5);
	turn(0, -40, 0, tireDistance/2, 27.5);



	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 25.0);
	lfPDline(40, true, true);
	resetMotorEncoder(motor_drive_right);

	// goto red manzgi

	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 18.0);
	driveCm(40, 40, 63.0);
	setMotorTarget(motor_grab, 520, 30);
	lfPDline(15, true, true);
	resetMotorEncoder(motor_drive_right);
	lfPDcm(15, 7);
	turn(0,-40,0,0,89);
	resetMotorEncoder(motor_drive_right);

	lfPDcm(40, 22.0);
	brake(40, 27.0);

	setMotorTarget(motor_grab, 180, 15);
	waitUntilMotorStop(motor_grab);

	turn(0, 40, 0, -tireDistance/2, 180);
	resetMotorEncoder(motor_drive_right);
	driveCm(15, 15, 20);
	turn(0, 40, 0, tireDistance/2, 90);
	resetMotorEncoder(motor_drive_right);

	driveCm(40, 40, 37.0);
	lfPDline(15, true, true);
	resetMotorEncoder(motor_drive_right);

	lfPDcm(40, 45);
	turn(0, 40, 0, -tireDistance/2, 90);
	resetMotorEncoder(motor_drive_right);
	driveCm(40, 40, 11);
	brake(40, 16);

	setMotorTarget(motor_grab, 520, 40);
	waitUntilMotorStop(motor_grab);

	resetMotorEncoder(motor_drive_right);
	driveCm(15, 15, 4);

	turn(0, 40, 0, -tireDistance/2, 45);
	delay(250);
	turn(0, -40, 0, -tireDistance/2, 45);

	resetMotorEncoder(motor_drive_right);
	driveCm(-40, -40, 23);
	brake(-40, 27);

	turn(0, -40, 0, 0, 90);
	resetMotorEncoder(motor_drive_right);
	lfPDcm(40, 40);
	lfPDline(40, true, true);
	end();



	brake(0, 0);
	eraseDisplay();
	displayCenteredBigTextLine(4, "%d.0 s", (float)time100[T4]/10.0);
	writeDebugStreamLine("TIME: %d", (float)time100[T4]/10.0);
	delay(10000);
	stopAllTasks();
}
